client_id = "617a7dbdcbf7a5f4b716cbe32d18d9b2"
name = "Painel UTM_2"
application_url = "https://example.com"
embedded = true

[access_scopes]
scopes = "read_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/api/webhooks/shopify/orders-create"
